version: '3.8'
services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: gabuntu
      POSTGRES_PASSWORD: gabuntuPassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
