version: '3.8'
services:
  frontend:
      build: ./frontend
      ports:
        - "80:80"
  db:
    build: ./db
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: gabuntu
      POSTGRES_PASSWORD: gabuntuPassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  user_management:
    build: ./services/user_management
    container_name: user_management
    restart: always
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://gabuntu:gabuntuPassword@db:5432/mydb
    depends_on:
      - db

  authentication:
    build: ./services/authentication
    container_name: authentication
    restart: always
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://gabuntu:gabuntuPassword@db:5432/mydb
    depends_on:
      - db

  questionnaire:
    build: ./services/questionnaire
    container_name: questionnaire
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - db

  evaluation:
    build: ./services/evaluation
    container_name: evaluation
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      - db

  real_mark_track:
    build: ./services/real_mark_track
    container_name: real_mark_track
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      - db

  tyk_gateway:
    image: 'tykio/tyk-gateway:v4.0.0'
    ports:
      - '8080:8080'
    volumes:
      - './tyk_api_gateway/tyk.conf:/opt/tyk-gateway/tyk.conf'
      - './tyk_api_gateway/apis:/opt/tyk-gateway/apps'
    depends_on:
      - redis

  redis:
    image: 'redis:6.2-alpine'

volumes:
  db_data: