version: '3.8'
services:
  frontend:
      build: ./frontend
      container_name:  Frontend
      ports:
        - "80:80"
        
  db:
    build: ./db
    container_name: Database
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  registration:
    build: ./services/registration
    container_name: Registration
    restart: always
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DB_HOST=${DATABASE_HOST}
      - DB_PORT=5432
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
    depends_on:
      - db

  authentication:
    build: ./services/authentication
    container_name: Authentication
    restart: always
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5432/${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
    depends_on:
      - db

  questionnaire:
    build: ./services/questionnaire
    container_name: Questionnaire
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - db

  evaluation:
    build: ./services/evaluation
    container_name: Evaluation
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      - db

  real_mark:
    build: ./services/real_mark
    container_name: RealMark
    restart: always
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5432/${DATABASE_NAME}"
    ports:
      - "3005:3005"
    depends_on:
      - db

  tyk_gateway:
    image: 'tykio/tyk-gateway:v4.0.0'
    container_name: APIgateway
    ports:
      - '8080:8080'
    volumes:
      - './tyk_api_gateway/tyk.conf:/opt/tyk-gateway/tyk.conf'
      - './tyk_api_gateway/apis:/opt/tyk-gateway/apps'
    depends_on:
      - redis

  redis:
    image: 'redis:6.2-alpine'

volumes:
  db_data: