version: '3.8'
services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: gabuntu
      POSTGRES_PASSWORD: gabuntuPassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  user_management:
    build: ./microservices/user_management
    container_name: user_management
    restart: always
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://gabuntu:gabuntuPassword@db:5432/mydb
    depends_on:
      - db

  authentication:
    build: ./microservices/authentication
    container_name: authentication
    restart: always
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://gabuntu:gabuntuPassword@db:5432/mydb
    depends_on:
      - db

  tyk_gateway:
    image: 'tykio/tyk-gateway:v4.0.0'
    ports:
      - '8080:8080'
    volumes:
      - './tyk_api_gateway/tyk.conf:/opt/tyk-gateway/tyk.conf'
      - './tyk_api_gateway/apis:/opt/tyk-gateway/apps'
    depends_on:
      - redis

  redis:
    image: 'redis:6.2-alpine'
